### PR TITLE
HRCPP-235 fixed VS2012 compile problem + minor changes

### PR DESCRIPTION
**Pull request by rigazilla**

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 501](http://ci.infinispan.org/viewLog.html?buildId=36343&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 806cf210ce7c5163452c06f376a2aaa877c49bd2
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:40

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 500](http://ci.infinispan.org/viewLog.html?buildId=36342&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 806cf210ce7c5163452c06f376a2aaa877c49bd2
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:10:00

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 503](http://ci.infinispan.org/viewLog.html?buildId=36350&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 806cf210ce7c5163452c06f376a2aaa877c49bd2
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:44

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 353](http://ci.infinispan.org/viewLog.html?buildId=36348&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 806cf210ce7c5163452c06f376a2aaa877c49bd2
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:10:57

**Pull request closed without merging**
