### PR TITLE
HRCPP-244 Fix to handle return value correctly

### PR DESCRIPTION
**Pull request by rigazilla**

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 381](http://ci.infinispan.org/viewLog.html?buildId=37783&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for f961cb1a87d05c214274fff2c8c57d99fb658875
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:00

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 382](http://ci.infinispan.org/viewLog.html?buildId=37785&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for dcbd31b5d7aaf897de7efc74e70be39949d9766d
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:23

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 537](http://ci.infinispan.org/viewLog.html?buildId=37782&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for dcbd31b5d7aaf897de7efc74e70be39949d9766d
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:55

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 538](http://ci.infinispan.org/viewLog.html?buildId=37818&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 03c57722b81c9d0a604c21bddb9e4581b52d9129
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:50

Process exited with code 8

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 383](http://ci.infinispan.org/viewLog.html?buildId=37817&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 03c57722b81c9d0a604c21bddb9e4581b52d9129
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:55

Process exited with code 255

**Comment by tristantarrant** [comment]
I get 3: 
3: These test should fail (but don't!):
3: 	CrossLanguageHotRodTest.testCppReplace
3: 	HotRodIntegrationTest.testReplaceWithPrevious

**Comment by rigazilla** [comment]
Yea I forgot to remove the fixed tests from the "test that should fail" list. 
Now should be ok

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 539](http://ci.infinispan.org/viewLog.html?buildId=37838&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 64fd756ff9f2ab05e940d0ced4cae7a32053ff3a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:04:48

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 384](http://ci.infinispan.org/viewLog.html?buildId=37837&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 64fd756ff9f2ab05e940d0ced4cae7a32053ff3a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:04

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 541](http://ci.infinispan.org/viewLog.html?buildId=37845&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 64fd756ff9f2ab05e940d0ced4cae7a32053ff3a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:04:36

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 386](http://ci.infinispan.org/viewLog.html?buildId=37843&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 64fd756ff9f2ab05e940d0ced4cae7a32053ff3a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:00

**Pull request closed without merging**
