### PR TITLE
HRCPP-198 Add infinispan.client.hotrod.max_retries equivalent

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.jboss.org/browse/HRCPP-198

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 233](http://ci.infinispan.org/viewLog.html?buildId=30821&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 189b5922b94ca95ec121b12c59bdb25b3c53f73f
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:50

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL6 [Build 263](http://ci.infinispan.org/viewLog.html?buildId=30822&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 189b5922b94ca95ec121b12c59bdb25b3c53f73f
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:59

Process exited with code 127

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL6 [Build 264](http://ci.infinispan.org/viewLog.html?buildId=30823&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 189b5922b94ca95ec121b12c59bdb25b3c53f73f
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:06

Process exited with code 127

**Comment by pruivo** [comment]
@alanfx comment fixed.

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL6 [Build 266](http://ci.infinispan.org/viewLog.html?buildId=30886&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 1cec81befca2d7501c001c64e914c6ff78d38bca
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:14

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL6 [Build 265](http://ci.infinispan.org/viewLog.html?buildId=30885&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 1cec81befca2d7501c001c64e914c6ff78d38bca
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:32

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 234](http://ci.infinispan.org/viewLog.html?buildId=30884&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 1cec81befca2d7501c001c64e914c6ff78d38bca
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:08

**Comment by alanfx** [comment]
Thanks, @pruivo. I was also able to run a test to verify that the mexRetries value is set correctly. This is ready to pull, but I don't have the permissions to do it!

**Comment by pruivo** [comment]
@tristantarrant can you have a look?

**Comment by tristantarrant** [comment]
Merged, thanks @pruivo

**Pull request merged**
