### PR TITLE
HRCPP-223 fix source zip package content

### PR DESCRIPTION
**Pull request by rigazilla**
fix source package content

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 276](http://ci.infinispan.org/viewLog.html?buildId=34985&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for c960d21bc4464801bedb3600de5eddcaec71c687
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:04

Process exited with code 1

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 279](http://ci.infinispan.org/viewLog.html?buildId=35002&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for c960d21bc4464801bedb3600de5eddcaec71c687
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:02

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 373](http://ci.infinispan.org/viewLog.html?buildId=34986&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for c960d21bc4464801bedb3600de5eddcaec71c687
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:10

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 374](http://ci.infinispan.org/viewLog.html?buildId=34987&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for c960d21bc4464801bedb3600de5eddcaec71c687
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:14

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 375](http://ci.infinispan.org/viewLog.html?buildId=34988&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for c960d21bc4464801bedb3600de5eddcaec71c687
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:07

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 376](http://ci.infinispan.org/viewLog.html?buildId=34989&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for c960d21bc4464801bedb3600de5eddcaec71c687
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:10

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 377](http://ci.infinispan.org/viewLog.html?buildId=34990&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for c960d21bc4464801bedb3600de5eddcaec71c687
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:10

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 384](http://ci.infinispan.org/viewLog.html?buildId=35005&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for c960d21bc4464801bedb3600de5eddcaec71c687
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:14

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 385](http://ci.infinispan.org/viewLog.html?buildId=35006&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for c960d21bc4464801bedb3600de5eddcaec71c687
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:08

**Pull request closed without merging**
