### PR TITLE
Hrcpp 394/google test

### PR DESCRIPTION
**Pull request by rigazilla**
Add Google Test libs as xunit test framework.

New tests based on xunit will be placed under xunit-test folder.

https://issues.jboss.org/browse/HRCPP-394

### CODE REVIEW

**Comment by alanfx** [comment]
Hey @rigazilla is it possible to integrate the GoogleTest-based tests with `ctest`, so they get executed with the rest of the test suite?

**Comment by rigazilla** [comment]
@alanfx with the current PR version ctest starts google test at the end of the old tests list.

**Comment by alanfx** [comment]
@rigazilla hm, I am not seeing that when I build this PR. The SWIG tests are the last tests run from `ctest -V`. Are there new CMake variables that need to be defined to include them in the build?

**Comment by rigazilla** [comment]
@alanfx maybe you need to define -DHOTROD_JBOSS_HOME= 

If you already have JBOSS_HOME try list all the tests with: ctest -N you should see gtest from 36 to 45, if not try with a rebuild.
The CI machine works as expected with this pr:
[pr 300 log](http://ci.infinispan.org/job/Infinispan%20C++%20Client/view/change-requests/job/PR-300/4/console)

**Comment by alanfx** [comment]
@rigazilla got it working now, thanks! 👍

**Comment by alanfx** [comment]
Hey @rigazilla when I ran the build and tests, I get the following errors for the new tests:

```
      Start 43: xunit_ClearTest
Could not find executable ClearTest
Looked in the following places:
ClearTest
ClearTest
Release/ClearTest
Release/ClearTest
Debug/ClearTest
Debug/ClearTest
MinSizeRel/ClearTest
MinSizeRel/ClearTest
RelWithDebInfo/ClearTest
RelWithDebInfo/ClearTest
Deployment/ClearTest
Deployment/ClearTest
Development/ClearTest
Development/ClearTest

43: Test command:  "--gtest_output=xml:/artifacts/cpp-client/build/tests-output/"
Unable to find executable: ClearTest
43/45 Test #43: xunit_ClearTest ..................***Not Run   0.00 sec
```

And a similar error for `PutGetTest`.

**Comment by rigazilla** [comment]
Fixed static libs for linux

**Comment by rigazilla** [comment]
@alanfx did you try a run with the last changes?

**Comment by alanfx** [comment]
@rigazilla sorry, I haven't yet, but I'll do it now

**Comment by alanfx** [comment]
@rigazilla I ran everything, and the results are all there. The only odd thing is that there are two directories for the test results `build/test-output` and `build/tests-output`. Do you think these directories can be combined? If not, it's not a big deal, but it would be nicer to have all of the results in one place.

**Comment by rigazilla** [comment]
@alanfx sure, done.

**Comment by alanfx** [comment]
@rigazilla ok, looks good. Thank you!

**Pull request merged**
