### PR TITLE
HRCPP-219 Fix compilation issues on Mac OS X

### PR DESCRIPTION
**Pull request by alanfx**
Fix compilation issues in Time, update README.md, and remove some
disabled options in CMakeLists.txt

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 266](http://ci.infinispan.org/viewLog.html?buildId=34869&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 1a07f4b980f12361ad5325f4672416b1958d3c53
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:04

Process exited with code 1

**Comment by alanfx** [comment]
I have verified that this fix works on Windows and Linux as well

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 270](http://ci.infinispan.org/viewLog.html?buildId=34946&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 1a07f4b980f12361ad5325f4672416b1958d3c53
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:02

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 354](http://ci.infinispan.org/viewLog.html?buildId=34870&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 1a07f4b980f12361ad5325f4672416b1958d3c53
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:47

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 355](http://ci.infinispan.org/viewLog.html?buildId=34871&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 1a07f4b980f12361ad5325f4672416b1958d3c53
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:08

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 361](http://ci.infinispan.org/viewLog.html?buildId=34950&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 1a07f4b980f12361ad5325f4672416b1958d3c53
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:22

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 362](http://ci.infinispan.org/viewLog.html?buildId=34951&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 1a07f4b980f12361ad5325f4672416b1958d3c53
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:17

**Pull request closed without merging**
