### PR TITLE
HRCPP-257 Fixed mem leak in runConcurrentCodecWritesTest

### PR DESCRIPTION
**Pull request by rigazilla**
the leak was in the test not in the Coded. Fixed.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 453](http://ci.infinispan.org/viewLog.html?buildId=39438&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for ebd2b78cb18993f4b8f4b6e649941be118a1141a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:34

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 604](http://ci.infinispan.org/viewLog.html?buildId=39439&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for ebd2b78cb18993f4b8f4b6e649941be118a1141a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:15:19

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 455](http://ci.infinispan.org/viewLog.html?buildId=39495&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for ebd2b78cb18993f4b8f4b6e649941be118a1141a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:40

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 606](http://ci.infinispan.org/viewLog.html?buildId=39498&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for ebd2b78cb18993f4b8f4b6e649941be118a1141a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:08

**Pull request closed without merging**
