### PR TITLE
HRCPP-272 Removed Builder<T>

### PR DESCRIPTION
**Pull request by rigazilla**
Removed Builder<T>. This is related to jira:

https://issues.jboss.org/browse/HRCPP-272

part of this PR has gone by mistake with jira:

https://issues.jboss.org/browse/HRCPP-221

so they must go always together.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 618](http://ci.infinispan.org/viewLog.html?buildId=39858&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 0e247c24ed0d0b68ae0ea748b04d9e1ab1c46865
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:43

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 470](http://ci.infinispan.org/viewLog.html?buildId=39857&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 0e247c24ed0d0b68ae0ea748b04d9e1ab1c46865
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:19

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 619](http://ci.infinispan.org/viewLog.html?buildId=39866&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for cfc14942d5258a26aba886cdc33d85749567562c
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:44

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 471](http://ci.infinispan.org/viewLog.html?buildId=39865&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for cfc14942d5258a26aba886cdc33d85749567562c
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:30

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 620](http://ci.infinispan.org/viewLog.html?buildId=39869&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for cedeb75c0a6af2f8a49472b24b6cbadf31fceb62
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:07

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 472](http://ci.infinispan.org/viewLog.html?buildId=39868&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for cedeb75c0a6af2f8a49472b24b6cbadf31fceb62
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:53

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 621](http://ci.infinispan.org/viewLog.html?buildId=39872&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c236bf320fa5806aa8bdfdca63713127fb335ae
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:54

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 473](http://ci.infinispan.org/viewLog.html?buildId=39871&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 6c236bf320fa5806aa8bdfdca63713127fb335ae
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:04

**Comment by tristantarrant** [comment]
Pushed to master, thanks

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 629](http://ci.infinispan.org/viewLog.html?buildId=40403&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c236bf320fa5806aa8bdfdca63713127fb335ae
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:46

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 490](http://ci.infinispan.org/viewLog.html?buildId=40398&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 6c236bf320fa5806aa8bdfdca63713127fb335ae
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:15:17

Process exited with code 255

**Pull request closed without merging**
