### PR TITLE
HRCPP-278 added missing method removeWithVersionAsync

### PR DESCRIPTION
**Pull request by rigazilla**
added method and a little fix

### CODE REVIEW

**Comment by mgencur** [comment]
Can you add a simple test, please?

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 637](http://ci.infinispan.org/viewLog.html?buildId=40498&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 8113c4d82369e47d157a199c9993cbd0d277cf0a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:41

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 498](http://ci.infinispan.org/viewLog.html?buildId=40497&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 8113c4d82369e47d157a199c9993cbd0d277cf0a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:29

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 641](http://ci.infinispan.org/viewLog.html?buildId=40551&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 8113c4d82369e47d157a199c9993cbd0d277cf0a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:45

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 504](http://ci.infinispan.org/viewLog.html?buildId=40556&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 8113c4d82369e47d157a199c9993cbd0d277cf0a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:32

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 648](http://ci.infinispan.org/viewLog.html?buildId=40915&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6182f02faea7588e9d18d177452c7b0d0aa4ba8b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:47

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 513](http://ci.infinispan.org/viewLog.html?buildId=40914&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 6182f02faea7588e9d18d177452c7b0d0aa4ba8b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:09:04

**Comment by rvansa** [comment]
No objections, seems like just following the principle set up in the original implementation. Is there a test for goAsync?

**Comment by rigazilla** [comment]
@rvansa  In the Simple.cpp file there's a test for the get/put Async that generates the code from the goAsync template.

@mgencur with the last commit I'm counting 19 Async methods. If we want a test for each ones I think it's better to track this as a separate issue.

**Comment by rvansa** [comment]
OK, I am content with this PR.

**Comment by slaskawi** [comment]
Looks good to me!

**Comment by tristantarrant** [comment]
Pushed to master, thanks

**Pull request closed without merging**
