### PR TITLE
HRCPP-266 now the build builds one bitness at time

### PR DESCRIPTION
**Pull request by rigazilla**
Build for one architecture at a time

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 456](http://ci.infinispan.org/viewLog.html?buildId=39661&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for c1c0f8b9d909df05a775c7625d028075173db79e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:33

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 457](http://ci.infinispan.org/viewLog.html?buildId=39664&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 2a9d27faa2b71b5b7f5fd3a3c0b9257af0248bd8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:06

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 458](http://ci.infinispan.org/viewLog.html?buildId=39666&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 1dad9f6514e7a5dcabe601595bbd9c25e4fbcba6
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:06

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 459](http://ci.infinispan.org/viewLog.html?buildId=39668&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for c39362720791001c05e8db50125588d7d863eae8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:05

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 460](http://ci.infinispan.org/viewLog.html?buildId=39670&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 0029aa43f5b12b719407586c0ccecf3db86ad4c0
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:05

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 461](http://ci.infinispan.org/viewLog.html?buildId=39672&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 9553b9d30ce787ea3a300bff2dedb6aebcd3b851
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:53

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 607](http://ci.infinispan.org/viewLog.html?buildId=39662&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 9553b9d30ce787ea3a300bff2dedb6aebcd3b851
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:33

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 608](http://ci.infinispan.org/viewLog.html?buildId=39683&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 15193edca442f38cdbebbe559c6a85f3c7990deb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:13

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 462](http://ci.infinispan.org/viewLog.html?buildId=39682&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 15193edca442f38cdbebbe559c6a85f3c7990deb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:43

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 609](http://ci.infinispan.org/viewLog.html?buildId=39700&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for bf505b373c90c62c5221c3a04e657187435bba3a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:16

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 463](http://ci.infinispan.org/viewLog.html?buildId=39699&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for bf505b373c90c62c5221c3a04e657187435bba3a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:07

**Comment by tristantarrant** [comment]
Pushed to master, thanks

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 613](http://ci.infinispan.org/viewLog.html?buildId=39841&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for bf505b373c90c62c5221c3a04e657187435bba3a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:17

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 616](http://ci.infinispan.org/viewLog.html?buildId=39854&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for bf505b373c90c62c5221c3a04e657187435bba3a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:13

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 467](http://ci.infinispan.org/viewLog.html?buildId=39839&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for bf505b373c90c62c5221c3a04e657187435bba3a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:17

**Pull request closed without merging**
