### PR TITLE
Hrcpp 237/ping mandatory

### PR DESCRIPTION
**Pull request by rigazilla**
Removed pingOnStartup flag. Now always ping on startup

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 366](http://ci.infinispan.org/viewLog.html?buildId=37440&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 16a119eb47619b33e82d0cc54ebf8cda233548ec
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:02:49

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 522](http://ci.infinispan.org/viewLog.html?buildId=37441&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 16a119eb47619b33e82d0cc54ebf8cda233548ec
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:36

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 523](http://ci.infinispan.org/viewLog.html?buildId=37442&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 16a119eb47619b33e82d0cc54ebf8cda233548ec
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:09

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 524](http://ci.infinispan.org/viewLog.html?buildId=37443&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 16a119eb47619b33e82d0cc54ebf8cda233548ec
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:16

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 369](http://ci.infinispan.org/viewLog.html?buildId=37455&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 16a119eb47619b33e82d0cc54ebf8cda233548ec
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:02:30

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 525](http://ci.infinispan.org/viewLog.html?buildId=37444&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 16a119eb47619b33e82d0cc54ebf8cda233548ec
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:09

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 528](http://ci.infinispan.org/viewLog.html?buildId=37453&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 16a119eb47619b33e82d0cc54ebf8cda233548ec
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:04:42

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 371](http://ci.infinispan.org/viewLog.html?buildId=37476&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for d0228e512e55ede6e879a877795f8fde7e37a138
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:35

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 374](http://ci.infinispan.org/viewLog.html?buildId=37515&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for b24739765e8a3a493c65cdd36a94400228077b60
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:53

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 530](http://ci.infinispan.org/viewLog.html?buildId=37477&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for b24739765e8a3a493c65cdd36a94400228077b60
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 01:36:47

Process exited with code 8

**Comment by tristantarrant** [comment]
Pushed

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 378](http://ci.infinispan.org/viewLog.html?buildId=37538&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for b24739765e8a3a493c65cdd36a94400228077b60
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:04

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 536](http://ci.infinispan.org/viewLog.html?buildId=37537&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for b24739765e8a3a493c65cdd36a94400228077b60
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:08

**Pull request closed without merging**
