### PR TITLE
Hrcpp 216/unique ptr merged

### PR DESCRIPTION
**Pull request by rigazilla**
Replaced hr_scoped_ptr with std::unique_ptr

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 300](http://ci.infinispan.org/viewLog.html?buildId=35953&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 475c1e56a3ebcdd6014201384ee50b464a49f32b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:28

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 418](http://ci.infinispan.org/viewLog.html?buildId=35954&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 475c1e56a3ebcdd6014201384ee50b464a49f32b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:37

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 419](http://ci.infinispan.org/viewLog.html?buildId=35955&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 475c1e56a3ebcdd6014201384ee50b464a49f32b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:09

Process exited with code 2

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 420](http://ci.infinispan.org/viewLog.html?buildId=35956&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 475c1e56a3ebcdd6014201384ee50b464a49f32b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:37

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 421](http://ci.infinispan.org/viewLog.html?buildId=35957&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 475c1e56a3ebcdd6014201384ee50b464a49f32b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:31

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 422](http://ci.infinispan.org/viewLog.html?buildId=35958&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 475c1e56a3ebcdd6014201384ee50b464a49f32b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:36

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 423](http://ci.infinispan.org/viewLog.html?buildId=35959&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 475c1e56a3ebcdd6014201384ee50b464a49f32b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:35

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 320](http://ci.infinispan.org/viewLog.html?buildId=36223&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 475c1e56a3ebcdd6014201384ee50b464a49f32b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:41

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 468](http://ci.infinispan.org/viewLog.html?buildId=36229&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 475c1e56a3ebcdd6014201384ee50b464a49f32b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:11:01

Process exited with code 8

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 469](http://ci.infinispan.org/viewLog.html?buildId=36230&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 475c1e56a3ebcdd6014201384ee50b464a49f32b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:20

Process exited with code 8

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 470](http://ci.infinispan.org/viewLog.html?buildId=36231&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 475c1e56a3ebcdd6014201384ee50b464a49f32b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:38

Process exited with code 8

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 471](http://ci.infinispan.org/viewLog.html?buildId=36232&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 475c1e56a3ebcdd6014201384ee50b464a49f32b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:10:28

Process exited with code 8

**Pull request closed without merging**
