### PR TITLE
HRCPP-227 fix conditional compiling for windows

### PR DESCRIPTION
**Pull request by rigazilla**

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 284](http://ci.infinispan.org/viewLog.html?buildId=35258&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for ff28514a2ae93fed61989dc8cd9a2ecb54eddb71
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:04

Process exited with code 1

**Comment by tristantarrant** [comment]
Merged, thanks

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 286](http://ci.infinispan.org/viewLog.html?buildId=35264&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for ff28514a2ae93fed61989dc8cd9a2ecb54eddb71
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:02

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 396](http://ci.infinispan.org/viewLog.html?buildId=35259&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for ff28514a2ae93fed61989dc8cd9a2ecb54eddb71
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:09:03

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 397](http://ci.infinispan.org/viewLog.html?buildId=35260&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for ff28514a2ae93fed61989dc8cd9a2ecb54eddb71
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:22

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 399](http://ci.infinispan.org/viewLog.html?buildId=35266&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for ff28514a2ae93fed61989dc8cd9a2ecb54eddb71
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:24

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 400](http://ci.infinispan.org/viewLog.html?buildId=35267&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for ff28514a2ae93fed61989dc8cd9a2ecb54eddb71
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:32

**Pull request closed without merging**
