### PR TITLE
HRCPP-212 Minimal marshaller that speaks JBossMarshaller language

### PR DESCRIPTION
**Pull request by rigazilla**
This PR contains some spacing fixup changes gone lost with the merge of PR 180

### CODE REVIEW

**Comment by tristantarrant** [comment]
@rigazilla there are conflicts, can you rebase please ?

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 267](http://ci.infinispan.org/viewLog.html?buildId=34876&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for e8002dd4d078b03a71604f1a5f73ff462fea9fe7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:02

Process exited with code 1

**Comment by rigazilla** [comment]
rebased

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 269](http://ci.infinispan.org/viewLog.html?buildId=34945&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for e8002dd4d078b03a71604f1a5f73ff462fea9fe7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:02

Process exited with code 1

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 272](http://ci.infinispan.org/viewLog.html?buildId=34958&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for e8002dd4d078b03a71604f1a5f73ff462fea9fe7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:02

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 356](http://ci.infinispan.org/viewLog.html?buildId=34877&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e8002dd4d078b03a71604f1a5f73ff462fea9fe7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:10

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 357](http://ci.infinispan.org/viewLog.html?buildId=34878&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e8002dd4d078b03a71604f1a5f73ff462fea9fe7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:13

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 359](http://ci.infinispan.org/viewLog.html?buildId=34948&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e8002dd4d078b03a71604f1a5f73ff462fea9fe7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:10

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 360](http://ci.infinispan.org/viewLog.html?buildId=34949&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e8002dd4d078b03a71604f1a5f73ff462fea9fe7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:19

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 364](http://ci.infinispan.org/viewLog.html?buildId=34960&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e8002dd4d078b03a71604f1a5f73ff462fea9fe7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:12

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 365](http://ci.infinispan.org/viewLog.html?buildId=34961&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e8002dd4d078b03a71604f1a5f73ff462fea9fe7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:14

**Pull request closed without merging**
