### PR TITLE
Hrcpp 238/compat

### PR DESCRIPTION
**Pull request by rigazilla**
warn the user if the server has compatibility mode enabled.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 373](http://ci.infinispan.org/viewLog.html?buildId=37499&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 0b9d733c52975c515a57dc6c4634be8c31b1e63b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:00

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 532](http://ci.infinispan.org/viewLog.html?buildId=37498&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 0fec5bb4bb7b031aaa701f409f1c94268f3a2c46
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:31

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 375](http://ci.infinispan.org/viewLog.html?buildId=37523&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 0fec5bb4bb7b031aaa701f409f1c94268f3a2c46
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:47

**Comment by tristantarrant** [comment]
Pushed

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 380](http://ci.infinispan.org/viewLog.html?buildId=37548&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 0fec5bb4bb7b031aaa701f409f1c94268f3a2c46
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:01

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 533](http://ci.infinispan.org/viewLog.html?buildId=37522&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 0fec5bb4bb7b031aaa701f409f1c94268f3a2c46
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:13

**Pull request closed without merging**
