### PR TITLE
Hrcpp 233/buildbat

### PR DESCRIPTION
**Pull request by rigazilla**
please merge

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 326](http://ci.infinispan.org/viewLog.html?buildId=36261&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for e06406366ddf24b4569a043196938f5ac10b6625
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:37

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 490](http://ci.infinispan.org/viewLog.html?buildId=36264&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e06406366ddf24b4569a043196938f5ac10b6625
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:33

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 488](http://ci.infinispan.org/viewLog.html?buildId=36263&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e06406366ddf24b4569a043196938f5ac10b6625
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:54

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 489](http://ci.infinispan.org/viewLog.html?buildId=36262&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e06406366ddf24b4569a043196938f5ac10b6625
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:09:49

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 330](http://ci.infinispan.org/viewLog.html?buildId=36278&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for e06406366ddf24b4569a043196938f5ac10b6625
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:37

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 498](http://ci.infinispan.org/viewLog.html?buildId=36287&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e06406366ddf24b4569a043196938f5ac10b6625
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:15

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 499](http://ci.infinispan.org/viewLog.html?buildId=36288&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e06406366ddf24b4569a043196938f5ac10b6625
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:06

**Pull request closed without merging**
