### PR TITLE
Hrcpp 464/transactions

### PR DESCRIPTION
**Pull request by rigazilla**
This is enables the client to do transactional operation. 

Step to run operations in a transactional way are:

- create a remote cache manager with a configuration with transactions enabled
- get one or more transactional caches
- get the transaction manager
- begin a transaction with transactionManager.begin()
- do your stuff
- transactionManager.commit() or rollback()

test/SimpleTx.cpp is a simple usage example

https://issues.jboss.org/browse/HRCPP-464

### CODE REVIEW

**Comment by alanfx** [comment]
I'm seeing failures in the tests still after synching to the latest changes. Are there any new data requirements for these tests?:

```
The following tests FAILED:
	 13 - simpleTx (Child aborted)
	 14 - simpleTx-static (Child aborted)
	 75 - xunit_TransactionTest (SEGFAULT)

      Start 13: simpleTx

13: Test command: /artifacts/cpp-client/build/simpleTx
13: Test timeout computed to be: 1500
13: HotRod C++ Library version 8.1.0.SNAPSHOT
13: Protocol HotRod C++ client, protocol version: 2.0-topology_change-event
13: k2 is chlorine
13: k2 is null
13: k2 is chlorine
13: ERROR [RetryOnFailureOperation.h:89] Exception encountered, retry 9 of 10: java.lang.NullPointerException
13: pointer is null:94
13: terminate called after throwing an instance of 'std::exception'
13:   what():  std::exception
13/77 Test #13: simpleTx .........................***Exception: Child aborted  0.06 sec
test 14
      Start 14: simpleTx-static

14: Test command: /artifacts/cpp-client/build/simpleTx-static
14: Test timeout computed to be: 1500
14: HotRod C++ Library version 8.1.0.SNAPSHOT
14: Protocol HotRod C++ client, protocol version: 2.0-topology_change-event
14: k2 is chlorine
14: k2 is null
14: k2 is chlorine
14: ERROR [RetryOnFailureOperation.h:89] Exception encountered, retry 9 of 10: java.lang.NullPointerException
14: pointer is null:94
14: terminate called after throwing an instance of 'std::exception'
14:   what():  std::exception
14/77 Test #14: simpleTx-static ..................***Exception: Child aborted  0.03 sec

75: Test command: /artifacts/cpp-client/build/xunit-test/TransactionTest/TransactionTest "--gtest_output=xml:/artifacts/cpp-client/build/test-output/"
75: Test timeout computed to be: 1500
75: [==========] Running 11 tests from 1 test case.
75: [----------] Global test environment set-up.
75: [----------] 11 tests from TransactionTest
75: [ RUN      ] TransactionTest.ReadCommitted
75: ERROR [RetryOnFailureOperation.h:89] Exception encountered, retry 9 of 10: java.lang.NullPointerException
75: /artifacts/cpp-client/xunit-test/TransactionTest/TransactionTest.cpp:71: Failure
75: Expected: (rv1) != (nullptr), actual: 8-byte object <00-00 00-00 00-00 00-00> vs (nullptr)
75/77 Test #75: xunit_TransactionTest ............***Exception: SegFault  0.08 sec
```

**Comment by rigazilla** [comment]
@alanfx are you running an ispn 9.3.+ ? I had that failures with 9.2.3. 
I've rebased the code and exposed some objects for C#.

**Comment by alanfx** [comment]
Hey @rigazilla, updating to `9.3.1.Final` let the tests pass, but this brings up another question. Are the HotRod transaction operations in a new protocol? It seems like there should a more user friendly way to tell the client that they are trying to use a feature that doesn't exist on the server. Thanks

**Comment by rigazilla** [comment]
@alanfx in this specific case the protocol version is the same, servers < 9.3.x have an internal error and reply with an exception and usually the client reports the server exceptions as they are.

On a 9.3 server if the client tries to use a non transactional cache receives a more clear error:
java.lang.IllegalStateException: ISPN006020: Cache 'default' is not transactional to execute a client transaction

**Comment by alanfx** [comment]
Do you know why adding transactions was done this way? That's the whole purpose for the protocols, IMO.

**Comment by rigazilla** [comment]
Transactions are supposed to work in 2.7 also, it's probably just a fix added to 9.3 in this case.

**Comment by pruivo** [comment]
As far as I can tell, the version is only there to tell operation format. For example, the put request changes the format from 1.0 to 2.x. 
I had some discussion about it and it seems to go towards the version removal and the PING request will return the operation that the server would handle.

@rigazilla I've added 3 more operations to support recovery:
https://github.com/infinispan/infinispan/pull/6179/files#diff-f71520f53261506da7eb9e1a7d6ad284R318

In case you want to implement them already or wait until the PR is integrated :+1: 
The PREPARE_TX_2 extends the prepare request with 2 more fields (a boolean and a long). Ping me if you need help to interpret the .gr file

**Comment by rigazilla** [comment]
@pruivo thanks for your comment.
I'll track the new operations on a separate jira.

+1 for removing the protocol version

**Comment by alanfx** [comment]
Thanks for the comment, @pruivo. @rigazilla Since this is working with a 9.3.x server, I'll merge this.

**Pull request merged**
