### PR TITLE
HRCPP-221 remove ServerNameId class

### PR DESCRIPTION
**Pull request by rigazilla**
Removed ServerNameId class, useless since InetSocketAddress has been exposed for swig tests

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 464](http://ci.infinispan.org/viewLog.html?buildId=39828&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 74025e3750373cdfff44ffff3f5febd1d8c33244
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:03:44

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 610](http://ci.infinispan.org/viewLog.html?buildId=39829&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 74025e3750373cdfff44ffff3f5febd1d8c33244
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:37

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 465](http://ci.infinispan.org/viewLog.html?buildId=39830&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 0d095d8b7f288acbcd9da02200119e4c72d0aa9b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:03:25

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 611](http://ci.infinispan.org/viewLog.html?buildId=39831&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 0d095d8b7f288acbcd9da02200119e4c72d0aa9b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:29

**Comment by tristantarrant** [comment]
Pushed to master.

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 614](http://ci.infinispan.org/viewLog.html?buildId=39846&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 0d095d8b7f288acbcd9da02200119e4c72d0aa9b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:42

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 617](http://ci.infinispan.org/viewLog.html?buildId=39855&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 0d095d8b7f288acbcd9da02200119e4c72d0aa9b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:09

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 468](http://ci.infinispan.org/viewLog.html?buildId=39844&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 0d095d8b7f288acbcd9da02200119e4c72d0aa9b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:17

**Pull request closed without merging**
