### PR TITLE
MVSC correct into MSVC

### PR DESCRIPTION
**Pull request by rigazilla**
Corrected label for Ms Visual Studio Compiler

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 247](http://ci.infinispan.org/viewLog.html?buildId=33945&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 1f9ec2aa2dfdd564c08e3b446620d858fc365c79
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:05

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 317](http://ci.infinispan.org/viewLog.html?buildId=33946&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 1f9ec2aa2dfdd564c08e3b446620d858fc365c79
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:11:19

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 318](http://ci.infinispan.org/viewLog.html?buildId=33947&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 1f9ec2aa2dfdd564c08e3b446620d858fc365c79
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:09:18

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 251](http://ci.infinispan.org/viewLog.html?buildId=34028&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 1f9ec2aa2dfdd564c08e3b446620d858fc365c79
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:02

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 325](http://ci.infinispan.org/viewLog.html?buildId=34031&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 1f9ec2aa2dfdd564c08e3b446620d858fc365c79
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:09:10

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 326](http://ci.infinispan.org/viewLog.html?buildId=34032&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 1f9ec2aa2dfdd564c08e3b446620d858fc365c79
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:09:39

**Pull request closed without merging**
