### PR TITLE
Hrcpp 260/csharp queries

### PR DESCRIPTION
**Pull request by rigazilla**
expose query API based on vector<unsigned char> used by C#

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 596](http://ci.infinispan.org/viewLog.html?buildId=39162&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 18527fa671b39b38e5eb9a956113b35aaa79ea95
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:55

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 597](http://ci.infinispan.org/viewLog.html?buildId=39288&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for b55c26e2b9b0acb31d3b8cbdb63729a729a9484f
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:43

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 598](http://ci.infinispan.org/viewLog.html?buildId=39315&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for ad67dde06370506f20f0b73a61efd5eaa46ac1df
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:08

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 448](http://ci.infinispan.org/viewLog.html?buildId=39287&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for ad67dde06370506f20f0b73a61efd5eaa46ac1df
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:56

**Comment by tristantarrant** [comment]
This looks good ? Do you need to do more ?

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 449](http://ci.infinispan.org/viewLog.html?buildId=39338&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for ad67dde06370506f20f0b73a61efd5eaa46ac1df
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 01:01:34

**Comment by infinispanrelease** [comment]
**UNKNOWN** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 599](http://ci.infinispan.org/viewLog.html?buildId=39337&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for ad67dde06370506f20f0b73a61efd5eaa46ac1df
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 01:04:02

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 600](http://ci.infinispan.org/viewLog.html?buildId=39345&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for ad67dde06370506f20f0b73a61efd5eaa46ac1df
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:09:04

**Comment by rigazilla** [comment]
Should be all ok now

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 601](http://ci.infinispan.org/viewLog.html?buildId=39347&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 55b336438fbd229099b45955290a9710c459ab3a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:33

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 450](http://ci.infinispan.org/viewLog.html?buildId=39346&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for a6ac7bfd1d92d38291c5977d05bf03680913422a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:00

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 602](http://ci.infinispan.org/viewLog.html?buildId=39349&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for a6ac7bfd1d92d38291c5977d05bf03680913422a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:40

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 451](http://ci.infinispan.org/viewLog.html?buildId=39348&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for a6ac7bfd1d92d38291c5977d05bf03680913422a
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:44

**Pull request merged**
