### PR TITLE
HRCPP-225 removed ScopedBuffer

### PR DESCRIPTION
**Pull request by rigazilla**
ScopedBuffer replaced with std::vector<char>. All tests passed... seems good.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 283](http://ci.infinispan.org/viewLog.html?buildId=35111&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for f077042809c63d782225f8827974e85a0f091699
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:04

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 394](http://ci.infinispan.org/viewLog.html?buildId=35112&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for f077042809c63d782225f8827974e85a0f091699
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:57

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 395](http://ci.infinispan.org/viewLog.html?buildId=35113&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for f077042809c63d782225f8827974e85a0f091699
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:18

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 292](http://ci.infinispan.org/viewLog.html?buildId=35509&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for f077042809c63d782225f8827974e85a0f091699
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:41

Process exited with code 1

**Comment by tristantarrant** [comment]
I love when custom code can be dropped and replaced with library code. Pushed

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 295](http://ci.infinispan.org/viewLog.html?buildId=35516&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for f077042809c63d782225f8827974e85a0f091699
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:26

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 401](http://ci.infinispan.org/viewLog.html?buildId=35510&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for f077042809c63d782225f8827974e85a0f091699
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:10:04

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 405](http://ci.infinispan.org/viewLog.html?buildId=35520&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for f077042809c63d782225f8827974e85a0f091699
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:24

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 406](http://ci.infinispan.org/viewLog.html?buildId=35521&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for f077042809c63d782225f8827974e85a0f091699
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:26

**Pull request closed without merging**
