### PR TITLE
HRCPP-439 Fix path for protobuf generate header

### PR DESCRIPTION
**Pull request by rigazilla**
this fix the path for the protobuf generated files. With this the same include path i.e. "infinispan/hotrod/query.pb.h" works for the source repo and the rpm or zip.

https://issues.jboss.org/browse/HRCPP-439

### CODE REVIEW

**Comment by alanfx** [comment]
@rigazilla This looks good to me, but I'm seeing test failures with the query tests:

```
The following tests FAILED:
	  7 - queryTest (Child aborted)
	  8 - queryTest-static (Child aborted)
	 11 - continuousQueryTest (Child aborted)
	 12 - continuousQueryTest-static (Child aborted)
	 55 - xunit_QueryTest (Failed)
```

`queryTest` and `queryTest-static` both still fail due to ISPN-8542 which should be fixed in 9.2.0.Beta2: 

```
7: ERROR [RetryOnFailureOperation.h:84] Exception encountered, retry 9 of 10: java.lang.NumberFormatException: For input string: "_null_"
7: terminate called after throwing an instance of 'infinispan::hotrod::HotRodClientException'
7:   what():  java.lang.NumberFormatException: For input string: "_null_"
 7/57 Test  #7: queryTest ........................***Exception: Child aborted  0.33 sec
```

`continuousQueryTest` and `continuousQueryTest-static` both get a TransportException:

```
11: ERROR [RetryOnFailureOperation.h:84] Exception encountered, retry 9 of 10: write (host: 127.0.0.1 port: 11222) Bad file descriptor
11: terminate called after throwing an instance of 'infinispan::hotrod::TransportException'
11:   what():  write (host: 127.0.0.1 port: 11222) Bad file descriptor
11/57 Test #11: continuousQueryTest ..............***Exception: Child aborted  0.12 sec
```

Is this fixed by https://github.com/infinispan/cpp-client/pull/314?

`QueryTest.ProjectionTest` is failing, but I'm not sure why:

```
55: [ RUN      ] QueryTest.ProjectionTest
55: unknown file: Failure
55: Unknown C++ exception thrown in the test body.
55: [  FAILED  ] QueryTest.ProjectionTest (20 ms)
```

If these are all known and fixed issues, I can merge this.

**Comment by rigazilla** [comment]
@alanfx I had to update the .proto files to work with 9.1.3+. Now should be ok

**Comment by rigazilla** [comment]
@alanfx fixed, with 9.1.3+ ickle null needs to be treated as real null

**Comment by alanfx** [comment]
@rigazilla so this one needs to be rebased now, but I am also wondering if all of the `.proto` files need to have a line with the syntax specified? WDYT?

```
syntax = "proto2";
```

**Comment by rigazilla** [comment]
@alanfx  yeah, done and rebased

**Comment by alanfx** [comment]
@rigazilla ok, looks good. Merging...

**Pull request merged**
