### PR TITLE
HRCPP-234 fix compile error for windows

### PR DESCRIPTION
**Pull request by rigazilla**
missing include for windows

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 325](http://ci.infinispan.org/viewLog.html?buildId=36258&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for e76f8b59f2ef94a567605f7e9f6348d5c8c378bd
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:50

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 486](http://ci.infinispan.org/viewLog.html?buildId=36259&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e76f8b59f2ef94a567605f7e9f6348d5c8c378bd
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:36

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 487](http://ci.infinispan.org/viewLog.html?buildId=36260&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e76f8b59f2ef94a567605f7e9f6348d5c8c378bd
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:09:23

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 329](http://ci.infinispan.org/viewLog.html?buildId=36277&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for e76f8b59f2ef94a567605f7e9f6348d5c8c378bd
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:37

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 496](http://ci.infinispan.org/viewLog.html?buildId=36285&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e76f8b59f2ef94a567605f7e9f6348d5c8c378bd
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:06

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 497](http://ci.infinispan.org/viewLog.html?buildId=36286&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e76f8b59f2ef94a567605f7e9f6348d5c8c378bd
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:10:04

**Pull request closed without merging**
