### PR TITLE
Hrcpp 221/balancing

### PR DESCRIPTION
**Pull request by rigazilla**
This let the user implements its own balancing strategy through servers. The user must derives an implementation from the class FailOverRequestBalancingStrategy and pass to the configuration builder a producer function for this class.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 311](http://ci.infinispan.org/viewLog.html?buildId=36160&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 0dbc134429d00cdc2ca3b64d9d2553bd881df961
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:57

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 312](http://ci.infinispan.org/viewLog.html?buildId=36165&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 8f065d0e4c2cbc6217fb4c52d00718cbfcbaebf9
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:50

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 313](http://ci.infinispan.org/viewLog.html?buildId=36168&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 8f065d0e4c2cbc6217fb4c52d00718cbfcbaebf9
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:52

Process exited with code 1

**Comment by infinispanrelease** [comment]
**UNKNOWN** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 314](http://ci.infinispan.org/viewLog.html?buildId=36169&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:04

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 315](http://ci.infinispan.org/viewLog.html?buildId=36170&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:04

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 316](http://ci.infinispan.org/viewLog.html?buildId=36173&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:44

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 455](http://ci.infinispan.org/viewLog.html?buildId=36161&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:28:37

Process exited with code 8

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 456](http://ci.infinispan.org/viewLog.html?buildId=36162&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:29

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 457](http://ci.infinispan.org/viewLog.html?buildId=36163&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:24

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 458](http://ci.infinispan.org/viewLog.html?buildId=36164&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:29

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 459](http://ci.infinispan.org/viewLog.html?buildId=36166&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:27

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 460](http://ci.infinispan.org/viewLog.html?buildId=36167&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:27

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 461](http://ci.infinispan.org/viewLog.html?buildId=36171&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:27

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 462](http://ci.infinispan.org/viewLog.html?buildId=36172&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:30

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 317](http://ci.infinispan.org/viewLog.html?buildId=36196&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:19

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 323](http://ci.infinispan.org/viewLog.html?buildId=36240&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:57

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 477](http://ci.infinispan.org/viewLog.html?buildId=36243&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:10:01

Process exited with code 8

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 478](http://ci.infinispan.org/viewLog.html?buildId=36244&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:26

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 483](http://ci.infinispan.org/viewLog.html?buildId=36253&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:09:51

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 484](http://ci.infinispan.org/viewLog.html?buildId=36254&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:46

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 485](http://ci.infinispan.org/viewLog.html?buildId=36255&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:10:00

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 482](http://ci.infinispan.org/viewLog.html?buildId=36252&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:30:13

Process exited with code 8

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 328](http://ci.infinispan.org/viewLog.html?buildId=36276&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:38

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 493](http://ci.infinispan.org/viewLog.html?buildId=36282&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:48

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 495](http://ci.infinispan.org/viewLog.html?buildId=36284&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:36

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 494](http://ci.infinispan.org/viewLog.html?buildId=36283&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6c1e6a2f1ee4145f231c07db4cbb794f8ff8a460
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:49

**Pull request closed without merging**
