### PR TITLE
HRCPP-280 memleak TcpTransport::readBytes()

### PR DESCRIPTION
**Pull request by rigazilla**
fixed mem leak in TcpTransport::readBytes()

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 495](http://ci.infinispan.org/viewLog.html?buildId=40481&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for d283e3b13f40dd98cbaf7ad5427fabb8174bb26e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:04:08

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 634](http://ci.infinispan.org/viewLog.html?buildId=40482&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for d283e3b13f40dd98cbaf7ad5427fabb8174bb26e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:49

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 638](http://ci.infinispan.org/viewLog.html?buildId=40500&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for d283e3b13f40dd98cbaf7ad5427fabb8174bb26e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:15

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 499](http://ci.infinispan.org/viewLog.html?buildId=40499&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for d283e3b13f40dd98cbaf7ad5427fabb8174bb26e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:28

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 640](http://ci.infinispan.org/viewLog.html?buildId=40550&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for d283e3b13f40dd98cbaf7ad5427fabb8174bb26e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:52

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 503](http://ci.infinispan.org/viewLog.html?buildId=40555&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for d283e3b13f40dd98cbaf7ad5427fabb8174bb26e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:28

**Comment by rvansa** [comment]
Looks ok :+1:

**Comment by tristantarrant** [comment]
Pushed to master. Thanks

**Pull request closed without merging**
