### PR TITLE
HRCPP-239 Native library loads at JniTest startup

### PR DESCRIPTION
**Pull request by rigazilla**
Load native library at the startup

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 354](http://ci.infinispan.org/viewLog.html?buildId=37215&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for b7a098d1c68880fb70c242f82e723f27a71a572e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:11:50

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 504](http://ci.infinispan.org/viewLog.html?buildId=37218&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for b7a098d1c68880fb70c242f82e723f27a71a572e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:17:16

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 505](http://ci.infinispan.org/viewLog.html?buildId=37219&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for b7a098d1c68880fb70c242f82e723f27a71a572e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:20

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 97](http://ci.infinispan.org/viewLog.html?buildId=37217&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for b7a098d1c68880fb70c242f82e723f27a71a572e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:07

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 355](http://ci.infinispan.org/viewLog.html?buildId=37232&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 997ec69896dee3bc7a08da7149831c64b42b12d8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:27

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 98](http://ci.infinispan.org/viewLog.html?buildId=37234&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 997ec69896dee3bc7a08da7149831c64b42b12d8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:57

**Comment by alanfx** [comment]
Looks good to me. Integrated!

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 357](http://ci.infinispan.org/viewLog.html?buildId=37242&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 997ec69896dee3bc7a08da7149831c64b42b12d8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:11:39

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 100](http://ci.infinispan.org/viewLog.html?buildId=37246&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 997ec69896dee3bc7a08da7149831c64b42b12d8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:36

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 506](http://ci.infinispan.org/viewLog.html?buildId=37235&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 997ec69896dee3bc7a08da7149831c64b42b12d8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:38

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 507](http://ci.infinispan.org/viewLog.html?buildId=37236&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 997ec69896dee3bc7a08da7149831c64b42b12d8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:04:31

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 509](http://ci.infinispan.org/viewLog.html?buildId=37248&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 997ec69896dee3bc7a08da7149831c64b42b12d8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:03

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 510](http://ci.infinispan.org/viewLog.html?buildId=37249&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 997ec69896dee3bc7a08da7149831c64b42b12d8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:19:58

**Pull request closed without merging**
