### PR TITLE
HRCPP-276 Updated build with static protobuf 2.6.1

### PR DESCRIPTION
**Pull request by rigazilla**
cmake changes to build with static protobuf 2.6.1

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 625](http://ci.infinispan.org/viewLog.html?buildId=40345&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 92d06f81e31aaa03a5383d84a2767da780720a46
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:38

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 478](http://ci.infinispan.org/viewLog.html?buildId=40344&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 92d06f81e31aaa03a5383d84a2767da780720a46
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:31:51

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 479](http://ci.infinispan.org/viewLog.html?buildId=40351&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for b482ec04084691dfed4048558f18ba4fa91ea0d4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:26

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 626](http://ci.infinispan.org/viewLog.html?buildId=40352&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for b482ec04084691dfed4048558f18ba4fa91ea0d4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:43

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 480](http://ci.infinispan.org/viewLog.html?buildId=40353&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for b482ec04084691dfed4048558f18ba4fa91ea0d4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:44

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 627](http://ci.infinispan.org/viewLog.html?buildId=40355&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 9c82244836efedb4cd9b3818f2e6cc8da769e81d
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:18

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 481](http://ci.infinispan.org/viewLog.html?buildId=40354&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 9c82244836efedb4cd9b3818f2e6cc8da769e81d
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:03

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 486](http://ci.infinispan.org/viewLog.html?buildId=40373&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 9c82244836efedb4cd9b3818f2e6cc8da769e81d
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:53

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 487](http://ci.infinispan.org/viewLog.html?buildId=40374&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 9c82244836efedb4cd9b3818f2e6cc8da769e81d
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:10:15

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 488](http://ci.infinispan.org/viewLog.html?buildId=40392&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 4ea432f3957347ca0192e76d792dff7649d6358e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:22:10

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 632](http://ci.infinispan.org/viewLog.html?buildId=40406&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 4ea432f3957347ca0192e76d792dff7649d6358e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:07

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 494](http://ci.infinispan.org/viewLog.html?buildId=40416&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 4ea432f3957347ca0192e76d792dff7649d6358e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:04

**Comment by tristantarrant** [comment]
Pushed to master, thanks

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 636](http://ci.infinispan.org/viewLog.html?buildId=40496&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 4ea432f3957347ca0192e76d792dff7649d6358e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:41

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 497](http://ci.infinispan.org/viewLog.html?buildId=40493&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 4ea432f3957347ca0192e76d792dff7649d6358e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:27

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 639](http://ci.infinispan.org/viewLog.html?buildId=40549&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 4ea432f3957347ca0192e76d792dff7649d6358e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:55

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 502](http://ci.infinispan.org/viewLog.html?buildId=40554&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 4ea432f3957347ca0192e76d792dff7649d6358e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:25

**Pull request closed without merging**
