### PR TITLE
HRCPP-205 Fix wrong typedef

### PR DESCRIPTION
**Pull request by rigazilla**

### CODE REVIEW

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 313](http://ci.infinispan.org/viewLog.html?buildId=32991&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for ee0e4362026bc2842e8b6226c06e868960ff2987
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:37

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 314](http://ci.infinispan.org/viewLog.html?buildId=32992&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for ee0e4362026bc2842e8b6226c06e868960ff2987
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:53

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 315](http://ci.infinispan.org/viewLog.html?buildId=32993&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for ee0e4362026bc2842e8b6226c06e868960ff2987
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:48

**Pull request merged**
