### PR TITLE
HRCPP-290 Removed ConfigurationChildBuilder class

### PR DESCRIPTION
**Pull request by rigazilla**
Removed ConfigurationChildBuilder not used for now.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 645](http://ci.infinispan.org/viewLog.html?buildId=40754&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for ff26b42d326a972f2230f4ce44b4df30bc4cfa60
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:10

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 508](http://ci.infinispan.org/viewLog.html?buildId=40753&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for ff26b42d326a972f2230f4ce44b4df30bc4cfa60
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:20:27

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 511](http://ci.infinispan.org/viewLog.html?buildId=40896&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for ff26b42d326a972f2230f4ce44b4df30bc4cfa60
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:20

**Comment by tristantarrant** [comment]
Pushed to master

**Pull request closed without merging**
