### PR TITLE
HRCPP-274 Some changes to reduce warnings

### PR DESCRIPTION
**Pull request by rigazilla**
Suppress some warning on the generated protobuf code, plus some fixes

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 622](http://ci.infinispan.org/viewLog.html?buildId=39918&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for c7af3d4e4b392410bfe12a0db9cb22e019eaf356
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:03:35

Process exited with code 2

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 474](http://ci.infinispan.org/viewLog.html?buildId=39917&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for c7af3d4e4b392410bfe12a0db9cb22e019eaf356
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:48

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 623](http://ci.infinispan.org/viewLog.html?buildId=39919&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 071204546ec0ca3753d73e6ad6b8d689923f6fa3
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:14

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 475](http://ci.infinispan.org/viewLog.html?buildId=39920&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 071204546ec0ca3753d73e6ad6b8d689923f6fa3
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:25

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 630](http://ci.infinispan.org/viewLog.html?buildId=40404&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 071204546ec0ca3753d73e6ad6b8d689923f6fa3
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:52

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 491](http://ci.infinispan.org/viewLog.html?buildId=40399&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 071204546ec0ca3753d73e6ad6b8d689923f6fa3
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:22:16

**Comment by tristantarrant** [comment]
Pushed to master, thanks

**Pull request closed without merging**
