### PR TITLE
HRCPP-202 Implement maxTotal of ConnectionPoolConfigurationBuilder fo…

### PR DESCRIPTION
**Pull request by pruivo**
…r C++ client

https://issues.jboss.org/browse/HRCPP-202

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL6 [Build 273](http://ci.infinispan.org/viewLog.html?buildId=31879&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 421663720f8938673b7044ae3994bfb7f2ec1ad4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:02

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL6 [Build 274](http://ci.infinispan.org/viewLog.html?buildId=31880&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 421663720f8938673b7044ae3994bfb7f2ec1ad4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:09:06

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 239](http://ci.infinispan.org/viewLog.html?buildId=31878&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 421663720f8938673b7044ae3994bfb7f2ec1ad4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:18

**Comment by tristantarrant** [comment]
Pushed, sir

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL6 [Build 276](http://ci.infinispan.org/viewLog.html?buildId=32357&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 421663720f8938673b7044ae3994bfb7f2ec1ad4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:26

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL6 [Build 277](http://ci.infinispan.org/viewLog.html?buildId=32358&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 421663720f8938673b7044ae3994bfb7f2ec1ad4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:28

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 241](http://ci.infinispan.org/viewLog.html?buildId=32355&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 421663720f8938673b7044ae3994bfb7f2ec1ad4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:02

Process exited with code 1

**Pull request closed without merging**
