### PR TITLE
CPP-255 update server and java test to 9.0.0.

### PR DESCRIPTION
**Pull request by rigazilla**
added also a script to tag a release

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 567](http://ci.infinispan.org/viewLog.html?buildId=38677&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 66ac138124ab0f564697c1bcd8980bc8f5326e91
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:05

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 411](http://ci.infinispan.org/viewLog.html?buildId=38676&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 66ac138124ab0f564697c1bcd8980bc8f5326e91
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:46

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 412](http://ci.infinispan.org/viewLog.html?buildId=38702&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 66ac138124ab0f564697c1bcd8980bc8f5326e91
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:10:16

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 415](http://ci.infinispan.org/viewLog.html?buildId=38712&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 66ac138124ab0f564697c1bcd8980bc8f5326e91
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:28

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 419](http://ci.infinispan.org/viewLog.html?buildId=38725&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 66ac138124ab0f564697c1bcd8980bc8f5326e91
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:26

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 571](http://ci.infinispan.org/viewLog.html?buildId=38726&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 66ac138124ab0f564697c1bcd8980bc8f5326e91
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:15

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 421](http://ci.infinispan.org/viewLog.html?buildId=38729&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 66ac138124ab0f564697c1bcd8980bc8f5326e91
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:39

Process exited with code 255

**Pull request closed without merging**
