### PR TITLE
Hrcpp 251/get cache

### PR DESCRIPTION
**Pull request by rigazilla**
RemoteCacheManager now returns the same instance of RemoteCache for the same request.
getCache called with marshaller specified, just update the marshaller if the cache already exists.

Added code to simple.cpp to test this feature natively, since the same java test can't be wrapped correctly in swig.

plus build.sh stops if INFINISPAN_VERSION variable is not defined

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 547](http://ci.infinispan.org/viewLog.html?buildId=38159&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 2aa8c7c347d773ba9a87e5d7d6466c680d20d735
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:04:42

Process exited with code 8

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 546](http://ci.infinispan.org/viewLog.html?buildId=38157&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 2aa8c7c347d773ba9a87e5d7d6466c680d20d735
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:43

Process exited with code 8

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 390](http://ci.infinispan.org/viewLog.html?buildId=38156&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 2aa8c7c347d773ba9a87e5d7d6466c680d20d735
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:14

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 548](http://ci.infinispan.org/viewLog.html?buildId=38165&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 718efe8926aaa7c6a209b5942664de8b0a32c03b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:37

Process exited with code 8

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 549](http://ci.infinispan.org/viewLog.html?buildId=38167&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 718efe8926aaa7c6a209b5942664de8b0a32c03b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:09

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 391](http://ci.infinispan.org/viewLog.html?buildId=38166&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 718efe8926aaa7c6a209b5942664de8b0a32c03b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:35

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 573](http://ci.infinispan.org/viewLog.html?buildId=38734&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 718efe8926aaa7c6a209b5942664de8b0a32c03b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:04:46

Process exited with code 8

**Comment by tristantarrant** [comment]
Looks good. Pushed.

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 422](http://ci.infinispan.org/viewLog.html?buildId=38735&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 718efe8926aaa7c6a209b5942664de8b0a32c03b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:51

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 424](http://ci.infinispan.org/viewLog.html?buildId=38744&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 718efe8926aaa7c6a209b5942664de8b0a32c03b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:52

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 575](http://ci.infinispan.org/viewLog.html?buildId=38740&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 718efe8926aaa7c6a209b5942664de8b0a32c03b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:38

Process exited with code 8

**Pull request closed without merging**
