### PR TITLE
HRCPP-248 Implemented hotrod size op

### PR DESCRIPTION
**Pull request by rigazilla**
hotrod size operation

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 542](http://ci.infinispan.org/viewLog.html?buildId=37957&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 70bbb5703884044493529f0e4bad3869af909310
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:16:57

Process exited with code 8

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 543](http://ci.infinispan.org/viewLog.html?buildId=37960&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e1706cbf65ca34410aa90c511317d7214eeb14a1
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:16:33

Process exited with code 8

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 387](http://ci.infinispan.org/viewLog.html?buildId=37956&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for e1706cbf65ca34410aa90c511317d7214eeb14a1
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:10

**Comment by tristantarrant** [comment]
Pushed to master, thanks

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 389](http://ci.infinispan.org/viewLog.html?buildId=38117&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for e1706cbf65ca34410aa90c511317d7214eeb14a1
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:12

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 545](http://ci.infinispan.org/viewLog.html?buildId=38120&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for e1706cbf65ca34410aa90c511317d7214eeb14a1
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:13

**Pull request closed without merging**
