### PR TITLE
Hrcpp 226/hrbytes merged

### PR DESCRIPTION
**Pull request by rigazilla**
This is a three step refactoring. Maybe it worth to keep three separated commit.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 299](http://ci.infinispan.org/viewLog.html?buildId=35868&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 13bba10f575c8423bc902782407f666c5b13a8df
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:43

Process exited with code 1

**Comment by tristantarrant** [comment]
Please rebase this on master

**Comment by rigazilla** [comment]
rebased.

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 303](http://ci.infinispan.org/viewLog.html?buildId=36037&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 38f82a93c5fd7a3b0bd2a117248d91f7ff0d6bfb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:43

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 413](http://ci.infinispan.org/viewLog.html?buildId=35869&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 38f82a93c5fd7a3b0bd2a117248d91f7ff0d6bfb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:09:37

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 414](http://ci.infinispan.org/viewLog.html?buildId=35870&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 38f82a93c5fd7a3b0bd2a117248d91f7ff0d6bfb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:11

Process exited with code 2

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 415](http://ci.infinispan.org/viewLog.html?buildId=35871&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 38f82a93c5fd7a3b0bd2a117248d91f7ff0d6bfb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:39

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 416](http://ci.infinispan.org/viewLog.html?buildId=35872&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 38f82a93c5fd7a3b0bd2a117248d91f7ff0d6bfb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:48

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 417](http://ci.infinispan.org/viewLog.html?buildId=35873&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 38f82a93c5fd7a3b0bd2a117248d91f7ff0d6bfb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:33

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 427](http://ci.infinispan.org/viewLog.html?buildId=36038&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 38f82a93c5fd7a3b0bd2a117248d91f7ff0d6bfb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:54

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 428](http://ci.infinispan.org/viewLog.html?buildId=36039&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 38f82a93c5fd7a3b0bd2a117248d91f7ff0d6bfb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:10

Process exited with code 2

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 308](http://ci.infinispan.org/viewLog.html?buildId=36088&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 38f82a93c5fd7a3b0bd2a117248d91f7ff0d6bfb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:41

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 429](http://ci.infinispan.org/viewLog.html?buildId=36040&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 38f82a93c5fd7a3b0bd2a117248d91f7ff0d6bfb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:56

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 430](http://ci.infinispan.org/viewLog.html?buildId=36041&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 38f82a93c5fd7a3b0bd2a117248d91f7ff0d6bfb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:09:47

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 431](http://ci.infinispan.org/viewLog.html?buildId=36042&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 38f82a93c5fd7a3b0bd2a117248d91f7ff0d6bfb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:54

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 444](http://ci.infinispan.org/viewLog.html?buildId=36089&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 38f82a93c5fd7a3b0bd2a117248d91f7ff0d6bfb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:53

Process exited with code 8

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 445](http://ci.infinispan.org/viewLog.html?buildId=36090&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 38f82a93c5fd7a3b0bd2a117248d91f7ff0d6bfb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:48

Process exited with code 8

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 446](http://ci.infinispan.org/viewLog.html?buildId=36091&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 38f82a93c5fd7a3b0bd2a117248d91f7ff0d6bfb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:48

Process exited with code 8

**Comment by infinispanrelease** [comment]
**UNKNOWN** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 318](http://ci.infinispan.org/viewLog.html?buildId=36220&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 38f82a93c5fd7a3b0bd2a117248d91f7ff0d6bfb
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:38

Process exited with code 1

**Pull request closed without merging**
