### PR TITLE
HRCPP-220 updated requirements

### PR DESCRIPTION
**Pull request by rigazilla**
Updated requirements list and fixed a minor on build.sh

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 277](http://ci.infinispan.org/viewLog.html?buildId=34992&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 817aac401b84db8b928d16e6a5e897d4306d361e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:02

Process exited with code 1

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 281](http://ci.infinispan.org/viewLog.html?buildId=35011&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 817aac401b84db8b928d16e6a5e897d4306d361e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:02

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 378](http://ci.infinispan.org/viewLog.html?buildId=34993&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 817aac401b84db8b928d16e6a5e897d4306d361e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:08

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 379](http://ci.infinispan.org/viewLog.html?buildId=34994&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 817aac401b84db8b928d16e6a5e897d4306d361e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:13

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 380](http://ci.infinispan.org/viewLog.html?buildId=34995&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 817aac401b84db8b928d16e6a5e897d4306d361e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:09

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 381](http://ci.infinispan.org/viewLog.html?buildId=34996&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 817aac401b84db8b928d16e6a5e897d4306d361e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:11

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 382](http://ci.infinispan.org/viewLog.html?buildId=34997&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 817aac401b84db8b928d16e6a5e897d4306d361e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:17

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 389](http://ci.infinispan.org/viewLog.html?buildId=35016&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 817aac401b84db8b928d16e6a5e897d4306d361e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:13

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 390](http://ci.infinispan.org/viewLog.html?buildId=35017&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 817aac401b84db8b928d16e6a5e897d4306d361e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:13

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 391](http://ci.infinispan.org/viewLog.html?buildId=35018&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 817aac401b84db8b928d16e6a5e897d4306d361e
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:39

**Pull request closed without merging**
