### PR TITLE
HRCPP-213 Add ProtoBuf generation machinery

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/HRCPP-213

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 562](http://ci.infinispan.org/viewLog.html?buildId=38658&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for b0f716d0a7e6d42ecc8b57870219b4697001e2a6
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:08

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 404](http://ci.infinispan.org/viewLog.html?buildId=38657&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for b0f716d0a7e6d42ecc8b57870219b4697001e2a6
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:15

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 563](http://ci.infinispan.org/viewLog.html?buildId=38659&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for c77df7a378bc4d675c112d4a76206fc6945d7be4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:02

Process exited with code 2

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 564](http://ci.infinispan.org/viewLog.html?buildId=38661&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for c77df7a378bc4d675c112d4a76206fc6945d7be4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:06

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 405](http://ci.infinispan.org/viewLog.html?buildId=38660&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for c77df7a378bc4d675c112d4a76206fc6945d7be4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:09

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 565](http://ci.infinispan.org/viewLog.html?buildId=38663&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 3c807060a86b4359df0e1ab2d5aada95f001c5ee
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:05

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 406](http://ci.infinispan.org/viewLog.html?buildId=38662&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 3c807060a86b4359df0e1ab2d5aada95f001c5ee
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:08

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 566](http://ci.infinispan.org/viewLog.html?buildId=38664&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 3c807060a86b4359df0e1ab2d5aada95f001c5ee
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:08

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 408](http://ci.infinispan.org/viewLog.html?buildId=38669&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 3c807060a86b4359df0e1ab2d5aada95f001c5ee
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:08

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 409](http://ci.infinispan.org/viewLog.html?buildId=38670&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 3c807060a86b4359df0e1ab2d5aada95f001c5ee
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:07

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 410](http://ci.infinispan.org/viewLog.html?buildId=38671&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 3c807060a86b4359df0e1ab2d5aada95f001c5ee
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:02:14

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 413](http://ci.infinispan.org/viewLog.html?buildId=38706&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 3c807060a86b4359df0e1ab2d5aada95f001c5ee
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:02:35

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 414](http://ci.infinispan.org/viewLog.html?buildId=38710&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for ecab483cc913c5462e035133634ba9d859c430f1
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:15

**Comment by rigazilla** [comment]
Please add this option -DPROTOBUF_PROTOC_EXECUTABLE="%PROTOBUF_PROTOC_EXECUTABLE%"

in the build.bat cmake call, is needed by the CI machine to locate the protoc executable

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 568](http://ci.infinispan.org/viewLog.html?buildId=38709&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for ecab483cc913c5462e035133634ba9d859c430f1
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:00

**Comment by tristantarrant** [comment]
Ok, added

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 416](http://ci.infinispan.org/viewLog.html?buildId=38713&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 2ff36e60b61e1030396b6467525001c5b898f4c9
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:38

**Comment by rigazilla** [comment]
merged, thanks

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 417](http://ci.infinispan.org/viewLog.html?buildId=38715&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 2ff36e60b61e1030396b6467525001c5b898f4c9
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:36

**Pull request merged**
