### PR TITLE
Hrcpp 436/new cmake targets

### PR DESCRIPTION
**Pull request by rigazilla**
https://issues.jboss.org/browse/HRCPP-436
This adds two new target for the build:

- build_dist
- build_test

The intended use is as follows.

**Build the distribution pack**
no need for maven or gtest

cd build
cmake ..
cmake --build . --target build_dist
cpack

**Build test against prebuilt**
no need for the full build

cd build
cmake .. -DHOTROD_JBOSS_HOME=&lt;path to jboss&gt; -DHOTROD_PREBUILT_LIB_DIR=&lt;path to the client libs&gt;
cmake --build . --target build_test
ctest -V

If you want to use your system protobuf libraries you can add -DHR_USE_SYSTEM_PROTOBUF=ON to the cmake setup

### CODE REVIEW

**Comment by alanfx** [comment]
Hey @rigazilla, the  `build_dist` target is working for me, but the `build_test` is failing to configure. It is trying to find some of the dependencies that used to be built on Linux in the `HOTROD_PREBUILT_LIB_DIR` location.

```
CMake Error at CMakeLists.txt:346 (message):
  Cannot find protobuf static library in directory
  '/artifacts/cpp-client/build'.
```

I think this is true for all of the Protobuf dependencies on Linux, but not on Windows. I think `HOTROD_PREBUILT_LIB_DIR` should only be used to find the pre-built HotRod libraries on Linux.

**Comment by rigazilla** [comment]
@alanfx the hotrod library contains some binary protobuf objects an this force the user application to use the same protobuf library version. This is why we decided to ship the protobuf library used in the build with the hotrod package and the build_test uses those libraries for the build.

Currently the binary pack are built with protobuf version 2.5.0 for linux and 2.6.1 for win32, I've added an option -DHR_USE_SYSTEM_PROTOBUF=ON that force the cmake to use the system libraries if the version matches.

**Comment by alanfx** [comment]
@rigazilla I am still having issues with the `build_test` target on Fedora. I was able to run the configure with this command line:

```
cmake .. -DHOTROD_JBOSS_HOME=/home/jboss/infinispan-server-${ISPN_VERSION}.${ISPN_MILESTONE} -DHOTROD_PREBUILT_LIB_DIR=`pwd` -DHR_USE_SYSTEM_PROTOBUF=ON
```

But the `build_test` target failed again:

```
[ 10%] Built target gtest
[ 12%] Running C++ protocol buffer compiler on /artifacts/cpp-client/test/query_proto/bank-xunit.proto
/bin/sh: ../../../bin/protoc: No such file or directory
gmake[3]: *** [xunit-test/QueryTest/CMakeFiles/QueryTest.dir/build.make:62: xunit-test/QueryTest/bank-xunit.pb.cc] Error 127
gmake[2]: *** [CMakeFiles/Makefile2:2023: xunit-test/QueryTest/CMakeFiles/QueryTest.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:801: CMakeFiles/build_test.dir/rule] Error 2
gmake: *** [Makefile:402: build_test] Error 2
```

The Protobuf compiler isn't there:

```
[jboss@moby build]$ which protoc
/usr/bin/protoc
```

I will also say that the RPM for RHEL doesn't include any Protobuf libraries, so you, Jakub, and I should talk about this.

**Comment by rigazilla** [comment]
@alanfx yeah I forgot about the protoc executable. now should be ok.

**Comment by alanfx** [comment]
@rigazilla OK, I still can't make this work. I deleted everything in the build directory, then configured and executed the `build_dist` target. Then I copied `libhotrod-static.a`, `libhotrod.so`, `libhotrod.so.1.0`, and `libhotrod_protobuf.a` to the `dist` directory of the root. Then I deleted everything again in the build directory, then configured and executed the `build_test ` target.

```
[jboss@moby build]$ cmake .. -DHOTROD_JBOSS_HOME=/home/jboss/infinispan-server-${ISPN_VERSION}.${ISPN_MILESTONE} -DHOTROD_PREBUILT_LIB_DIR=../dist/ -DHR_USE_SYSTEM_PROTOBUF=ON
-- The C compiler identification is GNU 7.2.1
-- The CXX compiler identification is GNU 7.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
HOTROD_VERSION is 8.1.0.SNAPSHOT
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Protobuf: /usr/lib64/libprotobuf.so;-lpthread (found version "3.3.1")
CMake Error at CMakeLists.txt:256 (message):
  Cannot find HotRod dynamic library in directory '../dist/'.


-- Configuring incomplete, errors occurred!
See also "/artifacts/cpp-client/build/CMakeFiles/CMakeOutput.log".
See also "/artifacts/cpp-client/build/CMakeFiles/CMakeError.log".
```

I am clearly doing something wrong here...

**Comment by rigazilla** [comment]
yeah @alanfx, it's better to use an absolute path for the prebuilt: cmake does some tricks with the directories.

-DHOTROD_PREBUILT_LIB_DIR=dist/ could also work but I feel more safe with an abs path

**Comment by alanfx** [comment]
@rigazilla OK, using an absolute path got me further. (Can the build fail when using a relative path?) But I am still getting an error trying to compile `QueryTest`:

```
Scanning dependencies of target QueryTest
[ 13%] Building CXX object xunit-test/QueryTest/CMakeFiles/QueryTest.dir/QueryTest.cpp.o
In file included from /artifacts/cpp-client/include/infinispan/hotrod/RemoteCacheBase.h:12:0,
                 from /artifacts/cpp-client/include/infinispan/hotrod/RemoteCache.h:4,
                 from /artifacts/cpp-client/include/infinispan/hotrod/RemoteCacheManager.h:6,
                 from /artifacts/cpp-client/xunit-test/QueryTest/QueryTest.cpp:2:
/artifacts/cpp-client/include/infinispan/hotrod/Query.h:10:10: fatal error: infinispan/hotrod/query.pb.h: No such file or directory
 #include "infinispan/hotrod/query.pb.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[3]: *** [xunit-test/QueryTest/CMakeFiles/QueryTest.dir/build.make:70: xunit-test/QueryTest/CMakeFiles/QueryTest.dir/QueryTest.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:2024: xunit-test/QueryTest/CMakeFiles/QueryTest.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:801: CMakeFiles/build_test.dir/rule] Error 2
gmake: *** [Makefile:402: build_test] Error 2
```

The weird thing is that I can't find `query.pb.h` or `query.pb` in the source or build directory at all.

**Comment by rigazilla** [comment]
@alanfx I'm trying to guess.
You have to unpack the rpm and point the HOTROD_PREBUILT_LIB_DIR to the lib dir.
Copying only the libs is not enough. Currently the build is pointing your <gitroot>/dist directory for the libs and to the <gitroot>/dist/../include (that is <gitroot>/include) for the include files. But that directory is not equals to the rpm /usr/include, particularly it doesn't contain all the protobuf generate headers.

**Comment by alanfx** [comment]
@rigazilla ok, I was finally able to make this work on Fedora with these commands:

```
cmake ..
cmake --build . --target build_dist
rm -Rf *.cmake CMake* DartConfiguration.tcl Makefile
cmake .. -DHOTROD_JBOSS_HOME=/home/jboss/infinispan-server-${ISPN_VERSION}.${ISPN_MILESTONE} -DHOTROD_PREBUILT_LIB_DIR=`pwd` -DHR_USE_SYSTEM_PROTOBUF=ON
cmake --build . --target build_test
```

I still think we need to figure out the issues around the Protobuf, but I think this can be merged now.

**Comment by rigazilla** [comment]
@alanfx great! I'll write some notes about protobuf on the  jdg jira

**Comment by alanfx** [comment]
Merged. Thanks, @rigazilla!

**Pull request merged**
