### PR TITLE
HRCPP-3 TLS support via OpenSSL

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/HRCPP-3

Need to complete the tests for server CA validation and client certs

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 577](http://ci.infinispan.org/viewLog.html?buildId=38807&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 75c74d7403ce62c4a430de06eb4c6cb51744c9d7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:08

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 426](http://ci.infinispan.org/viewLog.html?buildId=38806&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 75c74d7403ce62c4a430de06eb4c6cb51744c9d7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:15

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 578](http://ci.infinispan.org/viewLog.html?buildId=38809&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 054a60f3a49aa7d1ad00d103926c3aedc8859791
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:10

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 427](http://ci.infinispan.org/viewLog.html?buildId=38808&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 054a60f3a49aa7d1ad00d103926c3aedc8859791
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:02:52

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 579](http://ci.infinispan.org/viewLog.html?buildId=38812&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 8412343473847a6ac7b00598dfd084ac730e372d
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:05

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 428](http://ci.infinispan.org/viewLog.html?buildId=38810&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 8412343473847a6ac7b00598dfd084ac730e372d
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:06

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 584](http://ci.infinispan.org/viewLog.html?buildId=38831&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 3a051a95fc916df8c01dc1b282b4d8328d77dc87
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:47

Process exited with code 8

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 433](http://ci.infinispan.org/viewLog.html?buildId=38830&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 3a051a95fc916df8c01dc1b282b4d8328d77dc87
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:08

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 585](http://ci.infinispan.org/viewLog.html?buildId=38833&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for cd38ffbeb362a61a1cf4c655f2d5e4b865924475
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:16

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 434](http://ci.infinispan.org/viewLog.html?buildId=38832&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for cd38ffbeb362a61a1cf4c655f2d5e4b865924475
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:31

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 588](http://ci.infinispan.org/viewLog.html?buildId=38838&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 3a051a95fc916df8c01dc1b282b4d8328d77dc87
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:45

Process exited with code 8

**Comment by tristantarrant** [comment]
CI Fails on an unrelated test

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 436](http://ci.infinispan.org/viewLog.html?buildId=38837&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 3a051a95fc916df8c01dc1b282b4d8328d77dc87
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:51

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 437](http://ci.infinispan.org/viewLog.html?buildId=38841&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 3a051a95fc916df8c01dc1b282b4d8328d77dc87
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:59

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 442](http://ci.infinispan.org/viewLog.html?buildId=38864&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for fd14e6b987ba4d7b029b7441cd030e93ba7cd366
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:02

**Comment by rigazilla** [comment]
merged thanks!

**Pull request merged**
