### PR TITLE
HRCPP-222 fix number of retries

### PR DESCRIPTION
**Pull request by rigazilla**
Fixed number of retries

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 273](http://ci.infinispan.org/viewLog.html?buildId=34971&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 10f025eddbbbc65ab88b0286ac6c6185a2bbc3a7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:04

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 275](http://ci.infinispan.org/viewLog.html?buildId=34981&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 10f025eddbbbc65ab88b0286ac6c6185a2bbc3a7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:02

Process exited with code 1

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 280](http://ci.infinispan.org/viewLog.html?buildId=35010&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 10f025eddbbbc65ab88b0286ac6c6185a2bbc3a7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:02

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 366](http://ci.infinispan.org/viewLog.html?buildId=34972&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 10f025eddbbbc65ab88b0286ac6c6185a2bbc3a7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:13

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 367](http://ci.infinispan.org/viewLog.html?buildId=34973&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 10f025eddbbbc65ab88b0286ac6c6185a2bbc3a7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:12

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 368](http://ci.infinispan.org/viewLog.html?buildId=34974&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 10f025eddbbbc65ab88b0286ac6c6185a2bbc3a7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:17

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 369](http://ci.infinispan.org/viewLog.html?buildId=34975&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 10f025eddbbbc65ab88b0286ac6c6185a2bbc3a7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:08

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 371](http://ci.infinispan.org/viewLog.html?buildId=34983&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 10f025eddbbbc65ab88b0286ac6c6185a2bbc3a7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:11

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 372](http://ci.infinispan.org/viewLog.html?buildId=34984&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 10f025eddbbbc65ab88b0286ac6c6185a2bbc3a7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:17

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 387](http://ci.infinispan.org/viewLog.html?buildId=35014&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 10f025eddbbbc65ab88b0286ac6c6185a2bbc3a7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:15

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 388](http://ci.infinispan.org/viewLog.html?buildId=35015&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 10f025eddbbbc65ab88b0286ac6c6185a2bbc3a7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:15

**Pull request closed without merging**
