### PR TITLE
HRCPP-213 Added classes and build info for protobuf

### PR DESCRIPTION
**Pull request by rigazilla**
Added .proto for queries. Generated classes are also committed committed, not stylish but ok for now. Cmake build has been updated according.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 559](http://ci.infinispan.org/viewLog.html?buildId=38646&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 22975890ac6fd7931f7c360aed6c63e7335deeb1
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:02:37

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 402](http://ci.infinispan.org/viewLog.html?buildId=38645&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 22975890ac6fd7931f7c360aed6c63e7335deeb1
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:37

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 560](http://ci.infinispan.org/viewLog.html?buildId=38647&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 22975890ac6fd7931f7c360aed6c63e7335deeb1
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:04:44

**Comment by tristantarrant** [comment]
Superseded by https://github.com/infinispan/cpp-client/pull/212

**Pull request closed without merging**
