### PR TITLE
HRCPP-169 Windows socket code takes a long time to fail when connecting ...

### PR DESCRIPTION
**Pull request by isavin**
...to a non-existent server

https://issues.jboss.org/browse/HRCPP-169

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 200](http://ci.infinispan.org/viewLog.html?buildId=23577&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 020cbf1b0aa4e870d3b2683b57b5636469639c7b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:18

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 201](http://ci.infinispan.org/viewLog.html?buildId=23595&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 020cbf1b0aa4e870d3b2683b57b5636469639c7b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:33

**Comment by isavin** [comment]
Pushed.

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 208](http://ci.infinispan.org/viewLog.html?buildId=26793&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 020cbf1b0aa4e870d3b2683b57b5636469639c7b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:33

Process exited with code 1

**Pull request closed without merging**
