### PR TITLE
HRCPP-201 Properly set sub-second socket timeouts

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/HRCPP-201

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 236](http://ci.infinispan.org/viewLog.html?buildId=31368&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for c5932ab1291b5ae987fcd79dd84953c55b1c5955
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:06

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL6 [Build 268](http://ci.infinispan.org/viewLog.html?buildId=31369&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for c5932ab1291b5ae987fcd79dd84953c55b1c5955
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:09:23

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL6 [Build 269](http://ci.infinispan.org/viewLog.html?buildId=31370&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for c5932ab1291b5ae987fcd79dd84953c55b1c5955
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:54

**Comment by alanfx** [comment]
Integrated! Thanks, @tristantarrant!

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 238](http://ci.infinispan.org/viewLog.html?buildId=31783&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for c5932ab1291b5ae987fcd79dd84953c55b1c5955
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:30

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL6 [Build 271](http://ci.infinispan.org/viewLog.html?buildId=31785&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for c5932ab1291b5ae987fcd79dd84953c55b1c5955
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:24

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL6 [Build 272](http://ci.infinispan.org/viewLog.html?buildId=31786&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for c5932ab1291b5ae987fcd79dd84953c55b1c5955
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:24

**Pull request closed without merging**
