### PR TITLE
HRCPP-208 execute() method implementation

### PR DESCRIPTION
**Pull request by rigazilla**
Hotrod execute implementation

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 297](http://ci.infinispan.org/viewLog.html?buildId=35764&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 2cb21f76174f66df8ac0bcd13d35acfafa1f6fa6
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:07

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 298](http://ci.infinispan.org/viewLog.html?buildId=35800&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 133b377141d4b63b3f0741919f16c820763421b7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:44

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 409](http://ci.infinispan.org/viewLog.html?buildId=35765&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 133b377141d4b63b3f0741919f16c820763421b7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:21

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 410](http://ci.infinispan.org/viewLog.html?buildId=35766&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 133b377141d4b63b3f0741919f16c820763421b7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:09

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 411](http://ci.infinispan.org/viewLog.html?buildId=35801&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 133b377141d4b63b3f0741919f16c820763421b7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:58

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 412](http://ci.infinispan.org/viewLog.html?buildId=35802&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 133b377141d4b63b3f0741919f16c820763421b7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:38

**Comment by tristantarrant** [comment]
Pushed, thanks.

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 302](http://ci.infinispan.org/viewLog.html?buildId=36031&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 133b377141d4b63b3f0741919f16c820763421b7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:44

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 425](http://ci.infinispan.org/viewLog.html?buildId=36033&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 133b377141d4b63b3f0741919f16c820763421b7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:09:00

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 426](http://ci.infinispan.org/viewLog.html?buildId=36034&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 133b377141d4b63b3f0741919f16c820763421b7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:56

**Pull request closed without merging**
