### PR TITLE
HRCPP-212 Minimal marshaller that speaks JBossMarshaller language

### PR DESCRIPTION
**Pull request by rigazilla**
Marshaller that can handle small strings and integers in JBossMarshaller syntax

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 255](http://ci.infinispan.org/viewLog.html?buildId=34210&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 1c02ead44841561517891abbd59f5624ee65fae7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:06

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 335](http://ci.infinispan.org/viewLog.html?buildId=34211&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 1c02ead44841561517891abbd59f5624ee65fae7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:09:07

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 336](http://ci.infinispan.org/viewLog.html?buildId=34212&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 1c02ead44841561517891abbd59f5624ee65fae7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:05

**Comment by tristantarrant** [comment]
We should include a test which demonstrates that it works

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 258](http://ci.infinispan.org/viewLog.html?buildId=34259&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 1c02ead44841561517891abbd59f5624ee65fae7
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:02

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 261](http://ci.infinispan.org/viewLog.html?buildId=34282&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 2403b042b068c774f644274f4d350c100d634ea5
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:05

Process exited with code 1

**Comment by rigazilla** [comment]
Modified Simple.cpp to execute basic test for each marshaller

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 340](http://ci.infinispan.org/viewLog.html?buildId=34262&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 2403b042b068c774f644274f4d350c100d634ea5
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:04

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 341](http://ci.infinispan.org/viewLog.html?buildId=34263&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 2403b042b068c774f644274f4d350c100d634ea5
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:10

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 346](http://ci.infinispan.org/viewLog.html?buildId=34283&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 2403b042b068c774f644274f4d350c100d634ea5
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:04

Error while applying patch: Read-only file system

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 347](http://ci.infinispan.org/viewLog.html?buildId=34284&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 2403b042b068c774f644274f4d350c100d634ea5
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:02

Error while applying patch: Read-only file system

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 262](http://ci.infinispan.org/viewLog.html?buildId=34308&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for d4938f01061334533ddde47cf191f160ebf04280
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:03

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 348](http://ci.infinispan.org/viewLog.html?buildId=34309&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for d4938f01061334533ddde47cf191f160ebf04280
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:36

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 349](http://ci.infinispan.org/viewLog.html?buildId=34310&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for d4938f01061334533ddde47cf191f160ebf04280
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:07

**Comment by vjuranek** [comment]
Hi,
I'm still not able to store any value into the cache with compatibility mode turned on, still fails with `java.io.IOException: Unsupported protocol version 76`. The code I'm using is bellow. I expect that this is not a bug in HR client, but rather lack of C++ knowledge on my side. So this is just a plea for providing some short documentation or example how to use it, as for dumb people like me the test is obviously not clear enough :smile: Thanks!

```c++
int main(int argc, char** argv) {
  ConfigurationBuilder builder;
  builder.addServer().host(argc > 1 ? argv[1] : "127.0.0.1").port(argc > 2 ? atoi(argv[2]) : 11222).protocolVersion(Configuration::PROTOCOL_VERSION_12);
  RemoteCacheManager cacheManager(builder.build(), false);

  Marshaller<std::string> *km = new BasicMarshaller<std::string>();
  void (*kd)(Marshaller<std::string> *) = &Marshaller<std::string>::destroy;
  Marshaller<std::string> *vm = new BasicMarshaller<std::string>();
  void (*vd)(Marshaller<std::string> *) = &Marshaller<std::string>::destroy;
  RemoteCache<std::string, std::string> cache = cacheManager.getCache<std::string, std::string>(km,kd,vm,vd);
  cacheManager.start();

  std::string k1("key1");
  std::string k2("key2");
  std::string v1("value1");
  std::string v2("value2");

  cache.clear();
  cache.put(k1, v1);
  cache.put(k2, v2);
  cacheManager.stop();
  return 0;
}
```

**Comment by rigazilla** [comment]
Hi,

km and vm variables must point to an instance of JBasicMarshaller not to a
BasicMarshaller (maybe my choice for the name it's little error prone).
I think that your test will work with this fix.

The developments are still ongoing on this side, documentation will follow.

Let me know if this works.

Vittorio

**Comment by vjuranek** [comment]
> maybe my choice for the name it's little error prone

IMHO it's fine, this is my fault not noticing it

> documentation will follow

great

> Let me know if this works.

yes, it works (and hopefully will be integrated soon, as this is IMHO very useful feature). Thanks for your help!

**Comment by tristantarrant** [comment]
@rigazilla PR looks great. Please fix formatting and spacing to be consistent with the rest of the code please.

**Comment by tristantarrant** [comment]
Pushed.

**Pull request closed without merging**
