### PR TITLE
Hrcpp 253/query merged

### PR DESCRIPTION
**Pull request by rigazilla**
Implementation of the Hotrod query operation.
A simple use/test case is provided in the QueryTest.cpp file.

Two new marshallers based on protobuf are also include.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 403](http://ci.infinispan.org/viewLog.html?buildId=38648&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 6a082981518c1cf79955040b89bcf8a19e6076d1
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:03:03

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 561](http://ci.infinispan.org/viewLog.html?buildId=38649&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 6a082981518c1cf79955040b89bcf8a19e6076d1
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:12

**Comment by infinispanrelease** [comment]
**UNKNOWN** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 407](http://ci.infinispan.org/viewLog.html?buildId=38668&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 6a082981518c1cf79955040b89bcf8a19e6076d1
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:04

Process exited with code 1

**Comment by tristantarrant** [comment]
Needs rebase

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 576](http://ci.infinispan.org/viewLog.html?buildId=38801&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for aacf46811bf53f50a5d56062cec61ec50cc8d3e2
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:02:36

Process exited with code 2

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 425](http://ci.infinispan.org/viewLog.html?buildId=38800&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for aacf46811bf53f50a5d56062cec61ec50cc8d3e2
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:03:07

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 580](http://ci.infinispan.org/viewLog.html?buildId=38816&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for b259f15bc797bfbcdb79499bf6b895f290b16007
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:03

Process exited with code 2

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 429](http://ci.infinispan.org/viewLog.html?buildId=38815&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for b259f15bc797bfbcdb79499bf6b895f290b16007
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:03:51

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 581](http://ci.infinispan.org/viewLog.html?buildId=38818&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 0f6cef73887d860283d691e5c46e8867f36dfc32
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:02:34

Process exited with code 2

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 430](http://ci.infinispan.org/viewLog.html?buildId=38817&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 0f6cef73887d860283d691e5c46e8867f36dfc32
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:03:46

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 582](http://ci.infinispan.org/viewLog.html?buildId=38820&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 0f6cef73887d860283d691e5c46e8867f36dfc32
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:02:33

Process exited with code 2

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 431](http://ci.infinispan.org/viewLog.html?buildId=38819&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 0f6cef73887d860283d691e5c46e8867f36dfc32
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:03:19

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 583](http://ci.infinispan.org/viewLog.html?buildId=38829&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 7a47adea4caed66346c7ead9ed57d240a70de3b0
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:12

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 432](http://ci.infinispan.org/viewLog.html?buildId=38828&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 7a47adea4caed66346c7ead9ed57d240a70de3b0
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:50

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 586](http://ci.infinispan.org/viewLog.html?buildId=38835&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for dce25df91d534eafc64604499e258f59a57154ec
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:03

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 587](http://ci.infinispan.org/viewLog.html?buildId=38836&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for dce25df91d534eafc64604499e258f59a57154ec
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:08

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 435](http://ci.infinispan.org/viewLog.html?buildId=38834&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for dce25df91d534eafc64604499e258f59a57154ec
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:05

Process exited with code 255

**Comment by tristantarrant** [comment]
Pushed, thanks

**Pull request closed without merging**
