### PR TITLE
HRCPP-207 Asynchronous implementation for get, put and replace methods

### PR DESCRIPTION
**Pull request by rigazilla**

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 363](http://ci.infinispan.org/viewLog.html?buildId=37407&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 8f6106e31b86ecae0a2def1e67b13756b1634a66
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:02:35

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 517](http://ci.infinispan.org/viewLog.html?buildId=37408&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 8f6106e31b86ecae0a2def1e67b13756b1634a66
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:16:35

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 518](http://ci.infinispan.org/viewLog.html?buildId=37409&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 8f6106e31b86ecae0a2def1e67b13756b1634a66
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:16:58

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 519](http://ci.infinispan.org/viewLog.html?buildId=37410&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 8f6106e31b86ecae0a2def1e67b13756b1634a66
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:18:03

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 365](http://ci.infinispan.org/viewLog.html?buildId=37431&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 51d4bf72cd6f5d23f27355703a1482e5fd47ee55
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:16

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 520](http://ci.infinispan.org/viewLog.html?buildId=37432&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 51d4bf72cd6f5d23f27355703a1482e5fd47ee55
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:08

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 521](http://ci.infinispan.org/viewLog.html?buildId=37433&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 51d4bf72cd6f5d23f27355703a1482e5fd47ee55
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:04:36

**Comment by tristantarrant** [comment]
I think you can now remove the unsupportedoperationexceptions from some tests, such as:

FAILED: testPutAsync
3: org.testng.TestException: 
3: Expected exception org.infinispan.client.hotrod.exceptions.RemoteCacheManagerNotStartedException but got java.lang.UnsupportedOperationException
3: 	at org.infinispan.client.jni.hotrod.JniTest.main(JniTest.java:68)
3: Expected exception org.infinispan.client.hotrod.exceptions.RemoteCacheManagerNotStartedException but got java.lang.UnsupportedOperationException
3: 	... 14 more
3: Caused by: java.lang.UnsupportedOperationException
3: 	at org.infinispan.client.hotrod.impl.RemoteCacheUnsupported.putAsync(RemoteCacheUnsupported.java:71)
3: 	at org.infinispan.client.hotrod.CacheManagerNotStartedTest.testPutAsync(CacheManagerNotStartedTest.java:78)
3: 	... 16 more
3: ... Removed 27 stack frames

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 370](http://ci.infinispan.org/viewLog.html?buildId=37456&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 51d4bf72cd6f5d23f27355703a1482e5fd47ee55
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:19

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 529](http://ci.infinispan.org/viewLog.html?buildId=37457&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 51d4bf72cd6f5d23f27355703a1482e5fd47ee55
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 01:03:36

**Comment by rigazilla** [comment]
There's no an easy way to implement java wrapper for C++ async method, hence on the swig side they will remain unsupported. I removed from the swig test suite the test methods that fail for this reason. There are test for async method in the Simple.cpp code.

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 372](http://ci.infinispan.org/viewLog.html?buildId=37495&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 0b6b3c956222b936c8a536beb7bcadd1b7e5b509
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:41

**Comment by alanfx** [comment]
@rigazilla and @tristantarrant this seems to put the whole testing strategy for the C++ client into question If we can't use the existing Java test suite to verify the asynchronous methods. Can you describe in more detail why it is not possible to make the SWIG tests work? Are there going to be other cases where this is true as we try to bring the C++ client into parity with Java? @mgencur?

**Comment by rigazilla** [comment]
@alanfx the point here is that the asynchronous methods in the RemoteCache interface return a Java Future class, if we want to call the C++ library via Java we need to imagine a java Future/c++ std::future SWIG wrapper, with all the multithreading aspects to keep in mind on both side. This is for sure overshooting if we focus on this single PR, because the tests I disabled do not test anything about asynchronous, they only aim test that if a no started remote cache is being call then  an exception is raised. 
Generally speaking @alanfx, I'm not aware of the test strategy but I understand your point and I also do not like test suite where tests are skipped. This is my theoretical approach. 
Practically in this case my opinion is that the possibility to reuse the java tests suite is a plus but SWIG can't do the magic to completely maps all the tests with zero effort. And also providing the adequate effort, does it worth? There are cases in which the wrapper is more complex that the code for the feature, running the java test in these cases what we are actually testing: the feature or the wrapper? In my opinion in these cases a good native test is the better choice.

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 531](http://ci.infinispan.org/viewLog.html?buildId=37496&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 0b6b3c956222b936c8a536beb7bcadd1b7e5b509
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:59

**Comment by tristantarrant** [comment]
Pushed

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 377](http://ci.infinispan.org/viewLog.html?buildId=37535&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 0b6b3c956222b936c8a536beb7bcadd1b7e5b509
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:32

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 535](http://ci.infinispan.org/viewLog.html?buildId=37536&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 0b6b3c956222b936c8a536beb7bcadd1b7e5b509
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:18

**Pull request closed without merging**
