### PR TITLE
Fix for bug HRCPP-215

### PR DESCRIPTION
**Pull request by rigazilla**
please integrate

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 256](http://ci.infinispan.org/viewLog.html?buildId=34213&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 669bf70bf59e8691df119d7dbdef869f80996d32
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:02

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 337](http://ci.infinispan.org/viewLog.html?buildId=34214&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 669bf70bf59e8691df119d7dbdef869f80996d32
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:05

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 338](http://ci.infinispan.org/viewLog.html?buildId=34215&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 669bf70bf59e8691df119d7dbdef869f80996d32
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:06

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 259](http://ci.infinispan.org/viewLog.html?buildId=34260&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 669bf70bf59e8691df119d7dbdef869f80996d32
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:00:02

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 342](http://ci.infinispan.org/viewLog.html?buildId=34264&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 669bf70bf59e8691df119d7dbdef869f80996d32
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:09

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 343](http://ci.infinispan.org/viewLog.html?buildId=34265&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for 669bf70bf59e8691df119d7dbdef869f80996d32
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:45

**Pull request closed without merging**
