### PR TITLE
HRCPP-230 Updated test suite to 8.1.2. See also JDG-18

### PR DESCRIPTION
**Pull request by rigazilla**
This updates the tests to 8.1.2

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 304](http://ci.infinispan.org/viewLog.html?buildId=36060&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for 0c553c0d4240b9cc618d2eedd3f2568ee20644d9
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:43

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - WIN_S2012 [Build 305](http://ci.infinispan.org/viewLog.html?buildId=36067&buildTypeId=HotRodCpp_PullRequestsMonitorWinS2012&guest=1) for adebdedf43f0d1fb0038dc1e8f03bcc9e237fa1f
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:30

Process exited with code 1

**Comment by alanfx** [comment]
Looks good to me. Thanks for fixing this @rigazilla!

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 432](http://ci.infinispan.org/viewLog.html?buildId=36061&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for adebdedf43f0d1fb0038dc1e8f03bcc9e237fa1f
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:09:05

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 434](http://ci.infinispan.org/viewLog.html?buildId=36063&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for adebdedf43f0d1fb0038dc1e8f03bcc9e237fa1f
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:03

Process exited with code 8

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 433](http://ci.infinispan.org/viewLog.html?buildId=36062&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for adebdedf43f0d1fb0038dc1e8f03bcc9e237fa1f
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:00

Process exited with code 8

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 435](http://ci.infinispan.org/viewLog.html?buildId=36068&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for adebdedf43f0d1fb0038dc1e8f03bcc9e237fa1f
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:55

Process exited with code 8

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C++ Client :: Pull requests monitor - RHEL [Build 436](http://ci.infinispan.org/viewLog.html?buildId=36069&buildTypeId=HotRodCpp_PullRequestsMonitorRhel6&guest=1) for adebdedf43f0d1fb0038dc1e8f03bcc9e237fa1f
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:44

Process exited with code 8

**Pull request merged**
